### ISSUE TITLE
Search broken

### ISSUE THREAD

**Issue by Schpidi** [eurodatacube/public-collections#210]
The search seems to be entirely broken currently and returning way to many results.

**Comment by gmilcinski** [comment]
@Developer1510  - please take a look. I.e. try "sinergise" or "EOxCloudless"

**Comment by Schpidi** [comment]
Search seems broken again, the items move around a little but the number of matching datasets always stays 87.

**Comment by dthiex** [comment]
@Schpidi Are you referring to https://collections.eurodatacube.com/? For me the search is working (note it's only based on the collection name). Collections can also be filtered based on tags but for that one needs to select a tag below the collection name.

@Developer1510 Was this always how it was working?

**Comment by Schpidi** [comment]
thx @dthiex it is working again. and yes, I was referring to https://collections.eurodatacube.com/.
