### ISSUE TITLE
Wrong custom script URL (breaks EDC Browser)

### ISSUE THREAD

**Issue by dthiex** [eurodatacube/public-collections#286]
URL in the collection metadata is not using the correct new endpoint (Follow up from: https://github.com/eurodatacube/public-collections/pull/284)

URL the Script is stored but the custom script repository: https://custom-scripts.sentinel-hub.com/custom-scripts/copernicus_services/global-land-cover/global_land_cover/script.js

URL in the public collection metadata: https://custom-scripts.sentinel-hub.com/copernicus_services/global_land_cover/global-land-cover/script.js

**Comment by dthiex** [comment]
Found 2 more that are not work (links are the wrong URLs in this repo):
- https://custom-scripts.sentinel-hub.com/copernicus_services/corine_land_cover/corine_land_cover/script.js
- https://custom-scripts.sentinel-hub.com/copernicus_services/corine_land_cover/corine_land_cover_accounting_layer/script.js

**Comment by jonasViehweger** [comment]
I checked as well and those are all that do not work. However I found two visualizations which do not work in the browser out of the box (population_density and Sea Ice Extent). The example links in the public collections repo do work but not when you navigate there from the edc browser interface.

**Comment by jonasViehweger** [comment]
Also, there are quite a few collections in the category Miscellaneous which could be moved to Copernicus Services (HRVPP, CORINE, Global Land Cover)

**Comment by dthiex** [comment]
> However I found two visualizations which do not work in the browser out of the box (population_density and Sea Ice Extent).

The population density one seems indeed to be broken (https://github.com/eurodatacube/public-collections/issues/288) the Sea Ice Extent works with the right date range and location.

> Also, there are quite a few collections in the category Miscellaneous which could be moved to Copernicus Services (HRVPP, CORINE, Global Land Cover)

I also noticed this and will create an internal issue. This was sorted correctly at some point and I don't know why it's not anymore.
